### ISSUE TITLE
Detalles en código

### ISSUE THREAD

**Issue by tracel3ss** [tanaxer01/hash-dis#1]
Revisando tu código, me di cuenta que hay colisión de hashes para strings sobre 161 caracteres, se generan coalisiones obteniendo el mismo hash. Esto sólo modificando el final del string, lo que evidencia un corte del hash resultante.
Adjunto evidencia para su corrección:
1. Para el String: 
```
Testaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```
Se obtuvo el hash:
```
47e02037d015ae03880bc1aca96e5391f961406e2bbd9394b393de6ae778f9bb
```
2. Para el String:
 ```
Testaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```
Se obtuvo el hash:
```
47e02037d015ae03880bc1aca96e5391f961406e2bbd9394b393de6ae778f9bb
```
Intenta corregirlo antes de clases, para no atrasarte con el hito 3.
Cualquier duda, no dudes en contactarme.
Saludos!

**Comment by tanaxer01** [comment]
@5m0k3r Listo, ahi lo arregle !!! era una tonteraa. Por desordenado se me habia olvidad que tenia que agregar otro arreglo en una parte y el hash que entregaba era solo el del ultimo bloque. Ahi lo arregle y le agrege un poco mas de randomnes.

Ahora los resultados son:
`Testaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`
> afbbd0cbc98fb662be199edc5223fd0e71d5e06cbb21fbae7f0b3a0280755e2e

`Testaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`

> ef008677b467edb6e614c02e00cd7d3e24959360fe5a878a17df42be53d48e61
